# Generated by Django 2.0 on 2019-10-07 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('auteur', models.CharField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('date_parution', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de parution')),
            ],
        ),
    ]
